
"use client";

import type { Language } from '@/types';
import type { ReactNode } from 'react';
import React, { createContext, useState, useContext, useEffect } from 'react';
import { usePathname, useRouter } from 'next/navigation';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  translations: Record<string, string>;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translationsData = {
  en: {
    appName: "Javanese Journey",
    dashboard: "Dashboard",
    flashcards: "Flashcards",
    quizzes: "Quizzes",
    pronunciation: "Pronunciation",
    progress: "Progress",
    goals: "Goals",
    grammar: "Grammar",
    grammarLessons: "Grammar Lessons",
    grammarLessonsOverview: "Grammar Lessons Overview",
    grammarManagement: "Grammar Management",
    admin: "Admin",
    adminDashboard: "Admin Dashboard",
    backToApp: "Back to App",
    toggleToDutch: "Switch to Dutch",
    toggleToEnglish: "Switch to English",
    welcome: "Welcome to Javanese Journey!",
    welcomeBack: "Welcome back,",
    days: "days",
    startLearning: "Start Learning",
    javanese: "Javanese",
    dutch: "Dutch",
    flip: "Flip",
    next: "Next",
    checkAnswer: "Check Answer",
    correct: "Correct!",
    incorrect: "Incorrect. The correct answer is:",
    yourAnswer: "Your answer",
    correctAnswer: "Correct answer",
    userXP: "User XP",
    learningStreak: "Learning Streak",
    badges: "Badges",
    noBadgesEarned: "No badges earned yet. Keep learning!",
    learningProgress: "Learning Progress",
    preferredLearningStyle: "Preferred Learning Style (optional)",
    timeAvailable: "Time Available Today (optional)",
    generateGoals: "Generate Goals",
    generateYourGoals: "Generate Your Goals",
    viewYourGoals: "View Your Goals",
    dailyGoals: "Daily Goals",
    explanation: "Explanation",
    wordsManagement: "Words Management",
    quizzesManagement: "Quizzes Management",
    usersManagement: "Users Management",
    usersManagementDesc: "View user data and manage roles.",
    badgesManagement: "Badges Management",
    badgesManagementDesc: "Create and manage achievement badges.",
    addNewWord: "Add New Word",
    addNewQuiz: "Add New Quiz",
    addNewLesson: "Add New Lesson",
    addNewBadge: "Add New Badge",
    editBadge: "Edit Badge",
    editBadgeDesc: "Modify the details of this badge.",
    addNewBadgeDesc: "Enter the details for the new badge.",
    badgeName: "Badge Name",
    badgeDescription: "Description",
    badgeIcon: "Icon Name (Lucide)",
    badgeIconHint: "Refer to lucide.dev for icon names. Common ones: Award, BookOpenCheck, Flame, StarIcon, Trophy.",
    badgeThreshold: "Threshold (optional number)",
    badgeSaved: "Badge Saved",
    badgeDeleted: "Badge Deleted",
    hasBeenRemoved: "has been removed.",
    hasBeenUpdated: "has been updated.",
    hasBeenAdded: "has been added.",
    editLesson: "Edit Lesson",
    lessonTitle: "Lesson Title",
    lessonCategory: "Category",
    lessonLevel: "Level",
    lessonStatus: "Status",
    lessonExplanation: "Explanation",
    lessonExamples: "Examples",
    addExample: "Add Example",
    removeExample: "Remove Example",
    exampleJavanese: "Javanese Sentence",
    exampleDutch: "Dutch Translation",
    exampleSpeechLevel: "Speech Level",
    attachQuizzes: "Attach Quizzes",
    attachWords: "Attach Vocabulary Words",
    embedExercises: "Embed Exercises",
    addExercise: "Add Exercise",
    removeExercise: "Remove Exercise",
    fillInTheBlankExercise: "Fill-in-the-Blank",
    sentenceWithPlaceholder: "Sentence with ____ placeholder",
    correctAnswerForBlank: "Correct Answer for Blank",
    hintForBlank: "Hint (optional)",
    viewUsers: "View Users",
    save: "Save",
    saveDraft: "Save Draft",
    publish: "Publish",
    cancel: "Cancel",
    confirmRemove: "Are you sure you want to delete this?",
    question: "Question",
    options: "Options",
    noGoalsGenerated: "Enter your progress and generate your daily goals!",
    noGoalsYet: "No goals generated yet. Let's create some!",
    loadingGoals: "Generating your personalized goals...",
    errorGeneratingGoals: "Could not generate goals. Please try again.",
    logout: "Logout",
    login: "Login",
    getStarted: "Get Started",
    tagline: "Your personal guide to mastering the Javanese language.",
    featureFlashcards: "Interactive Flashcards",
    featureFlashcardsDesc: "Master vocabulary with engaging flashcards.",
    featureQuizzes: "Challenging Quizzes",
    featureQuizzesDesc: "Test your knowledge with diverse quizzes.",
    featurePronunciation: "Audio Pronunciation",
    featurePronunciationDesc: "Perfect your accent with native audio.",
    featureAdaptiveGoals: "AI-Powered Goals",
    featureAdaptiveGoalsDesc: "Get daily learning goals tailored to you.",
    profile: "Profile",
    profileSettings: "Profile Settings",
    updateProfile: "Update Profile",
    learningPreferences: "Learning Preferences",
    dailyStudyGoal: "Daily Study Goal (minutes)",
    accountManagement: "Account Management",
    deleteAccount: "Delete Account",
    role: "Role",
    roles: "Roles",
    editor: "Editor",
    publisher: "Publisher",
    name: "Name",
    email: "Email",
    finishQuiz: "Finish Quiz",
    nextQuestion: "Next Question",
    selectQuizPrompt: "Select a quiz to begin.",
    quizCompleted: "Quiz Completed!",
    startQuiz: "Start Quiz",
    fillInTheBlanks: "Fill in the Blanks",
    fillintheblanks: "Fill in Blanks",
    fillInTheBlankInstruction: "Type the missing Javanese word.",
    nextExercise: "Next Exercise",
    typeYourAnswer: "Type your answer here...",
    showAnswer: "Show Answer",
    missingWordWas: "The missing word was:",
    noFillExercises: "No fill-in-the-blank exercises available at the moment.",
    noFillExercisesForLevel: "No fill-in-the-blank exercises available for the selected level. Try a different filter.",
    noHintAvailable: "No hint available.",
    showJavaneseFirst: "Show Javanese First",
    selectLevel: "Select Level",
    selectStatus: "Select Status",
    selectSpeechLevel: "Select Speech Level",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    allLevels: "All Levels",
    filterByLevel: "Filter by Level:",
    draft: "Draft",
    published: "Published",
    archived: "Archived",
    ngoko: "Ngoko (Informal)",
    krama: "Krama (Formeel)",
    madya: "Madya (Semi-formeel)",
    neutral: "Neutral",
    other: "Other",
    english: "English",
    lessonSaved: "Lesson Saved",
    lessonPublished: "Lesson Published",
    formValidationFailed: "Please check the form for errors.",
    noQuizzesAvailable: "No quizzes available to attach.",
    noWordsAvailable: "No vocabulary words available to attach.",
    lessonImageURL: "Lesson Image URL (optional)",
    lessonAudioURL: "Lesson Audio URL (optional)",
    imageURL: "Image URL",
    audioURL: "Audio URL",
    preview: "Preview (simulated)",
    translateWordDutch: "Translate word to Dutch:",
    translateSentenceDutch: "Translate sentence to Dutch:",
    translateWordJavanese: "Translate word to Javanese:",
    translateSentenceJavanese: "Translate sentence to Javanese:",
    fillInTheBlankMCQ: "Complete the sentence:",
    aiAssistContent: "AI Assist Content",
    aiAssistComplete: "AI Assistance Complete",
    aiAssistError: "AI Assist Error",
    manageUserRoles: "Manage User Roles",
    selectRolesForUser: "Select the roles for this user.",
    assignableRoles: "Assignable Roles",
    saveRoles: "Save Roles",
    userRolesUpdated: "User Roles Updated",
    rolesFor: "Roles for",
    haveBeenSaved: "have been saved.",
    todaysFocus: "Today's Focus",
    yourLearningJourney: "Your Learning Journey",
    continueLearning: "Continue Learning",
    resumeGrammar: "Resume Grammar:",
    tryNewQuiz: "Try a New Quiz:",
    practicePronunciation: "Practice Pronunciation:",
    discoverMore: "Discover More",
    yourAchievements: "Your Achievements",
    viewAllProgress: "View All Progress & Badges",
    viewedLesson: "Viewed lesson",
    lessonNotFound: "Lesson Not Found",
    lessonNotFoundDesc: "The grammar lesson you are looking for does not exist or could not be loaded.",
    backToLessons: "Back to Lessons",
    listenToLesson: "Listen to Lesson Overview",
    playingAudio: "Playing audio for",
    simulatingPlayback: "Simulating playback",
    audioNotAvailable: "Audio Not Available",
    noAudioFor: "No audio for",
    practiceExercises: "Practice Exercises",
    applyWhatLearned: "Apply what you've learned with these interactive exercises.",
    relatedVocabulary: "Related Vocabulary",
    keyWordsRelated: "Key words related to this lesson.",
    practiceInFlashcards: "Practice these words in Flashcards",
    relatedQuizzes: "Related Quizzes",
    testYourUnderstanding: "Test your understanding of concepts from this lesson.",
    lessonRelatesToQuiz: "This lesson relates to the quiz:",
    quizPageNote: "(This will take you to the main Quizzes page where you can select this quiz.)",
    tryAgain: "Try Again",
    checkMasteryAndComplete: "Check Mastery & Complete Lesson",
    masteryNote: "Mastery requires all embedded exercises to be correct on the first attempt.",
    completeAllExercises: "Incomplete",
    attemptAllEmbeddedExercises: "Please attempt all embedded exercises before checking mastery.",
    lessonMastered: "Lesson Mastered!",
    congratsPerfectEmbedded: "Congratulations! You completed all embedded exercises perfectly on the first try.",
    masteryNotAchieved: "Mastery Not Achieved",
    reviewAndRetryLesson: "Not all exercises were correct on the first try. Review the material and try the lesson again (e.g., by re-navigating) for a fresh attempt at mastery.",
  },
  nl: {
    appName: "Javaanse Reis",
    dashboard: "Dashboard",
    flashcards: "Flashcards",
    quizzes: "Quizzen",
    pronunciation: "Uitspraak",
    progress: "Voortgang",
    goals: "Doelen",
    grammar: "Grammatica",
    grammarLessons: "Grammaticalessen",
    grammarLessonsOverview: "Overzicht Grammaticalessen",
    grammarManagement: "Grammaticabeheer",
    admin: "Beheer",
    adminDashboard: "Beheerdersdashboard",
    backToApp: "Terug naar App",
    toggleToDutch: "Schakel naar Nederlands",
    toggleToEnglish: "Switch to English",
    welcome: "Welkom bij Javaanse Reis!",
    welcomeBack: "Welkom terug,",
    days: "dagen",
    startLearning: "Begin met Leren",
    javanese: "Javaans",
    dutch: "Nederlands",
    flip: "Omdraaien",
    next: "Volgende",
    checkAnswer: "Controleer Antwoord",
    correct: "Correct!",
    incorrect: "Incorrect. Het juiste antwoord is:",
    yourAnswer: "Jouw antwoord",
    correctAnswer: "Correct antwoord",
    userXP: "Gebruikers XP",
    learningStreak: "Leerreeks",
    badges: "Badges",
    noBadgesEarned: "Nog geen badges verdiend. Blijf leren!",
    learningProgress: "Leervoortgang",
    preferredLearningStyle: "Voorkeur Leerstijl (optioneel)",
    timeAvailable: "Beschikbare Tijd Vandaag (optioneel)",
    generateGoals: "Genereer Doelen",
    generateYourGoals: "Genereer Je Doelen",
    viewYourGoals: "Bekijk Je Doelen",
    dailyGoals: "Dagelijkse Doelen",
    explanation: "Uitleg",
    wordsManagement: "Woordenbeheer",
    quizzesManagement: "Quizbeheer",
    usersManagement: "Gebruikersbeheer",
    usersManagementDesc: "Bekijk gebruikersgegevens en beheer rollen.",
    badgesManagement: "Badgebeheer",
    badgesManagementDesc: "Creëer en beheer prestatiebadges.",
    addNewWord: "Nieuw Woord Toevoegen",
    addNewQuiz: "Nieuwe Quiz Toevoegen",
    addNewLesson: "Nieuwe Les Toevoegen",
    addNewBadge: "Nieuwe Badge Toevoegen",
    editBadge: "Badge Bewerken",
    editBadgeDesc: "Wijzig de details van deze badge.",
    addNewBadgeDesc: "Voer de details voor de nieuwe badge in.",
    badgeName: "Badge Naam",
    badgeDescription: "Beschrijving",
    badgeIcon: "Icoon Naam (Lucide)",
    badgeIconHint: "Raadpleeg lucide.dev voor icoonnamen. Veelgebruikte: Award, BookOpenCheck, Flame, StarIcon, Trophy.",
    badgeThreshold: "Drempel (optioneel getal)",
    badgeSaved: "Badge Opgeslagen",
    badgeDeleted: "Badge Verwijderd",
    hasBeenRemoved: "is verwijderd.",
    hasBeenUpdated: "is bijgewerkt.",
    hasBeenAdded: "is toegevoegd.",
    editLesson: "Les Bewerken",
    lessonTitle: "Les Titel",
    lessonCategory: "Categorie",
    lessonLevel: "Niveau",
    lessonStatus: "Status",
    lessonExplanation: "Uitleg",
    lessonExamples: "Voorbeelden",
    addExample: "Voorbeeld Toevoegen",
    removeExample: "Voorbeeld Verwijderen",
    exampleJavanese: "Javaanse Zin",
    exampleDutch: "Nederlandse Vertaling",
    exampleSpeechLevel: "Taalniveau",
    attachQuizzes: "Quizzen Koppelen",
    attachWords: "Woordenschat Koppelen",
    embedExercises: "Oefeningen Insluiten",
    addExercise: "Oefening Toevoegen",
    removeExercise: "Oefening Verwijderen",
    fillInTheBlankExercise: "Invuloefening",
    sentenceWithPlaceholder: "Zin met ____ plaatshouder",
    correctAnswerForBlank: "Correct Antwoord voor Leegte",
    hintForBlank: "Hint (optioneel)",
    viewUsers: "Bekijk Gebruikers",
    save: "Opslaan",
    saveDraft: "Concept Opslaan",
    publish: "Publiceren",
    cancel: "Annuleren",
    confirmRemove: "Weet u zeker dat u dit wilt verwijderen?",
    question: "Vraag",
    options: "Opties",
    noGoalsGenerated: "Voer je voortgang in en genereer je dagelijkse doelen!",
    noGoalsYet: "Nog geen doelen gegenereerd. Laten we er een paar maken!",
    loadingGoals: "Je gepersonaliseerde doelen worden gegenereerd...",
    errorGeneratingGoals: "Kon doelen niet genereren. Probeer het opnieuw.",
    logout: "Uitloggen",
    login: "Inloggen",
    getStarted: "Begin Nu",
    tagline: "Jouw persoonlijke gids om de Javaanse taal te beheersen.",
    featureFlashcards: "Interactieve Flashcards",
    featureFlashcardsDesc: "Beheers woordenschat met boeiende flashcards.",
    featureQuizzes: "Uitdagende Quizzen",
    featureQuizzesDesc: "Test je kennis met diverse quizzen.",
    featurePronunciation: "Audio Uitspraak",
    featurePronunciationDesc: "Perfectioneer je accent met authentieke audio.",
    featureAdaptiveGoals: "AI-gestuurde Doelen",
    featureAdaptiveGoalsDesc: "Ontvang dagelijkse leerdoelen op maat.",
    profile: "Profiel",
    profileSettings: "Profielinstellingen",
    updateProfile: "Profiel Bijwerken",
    learningPreferences: "Leervoorkeuren",
    dailyStudyGoal: "Dagelijks Studiedoel (minuten)",
    accountManagement: "Accountbeheer",
    deleteAccount: "Account Verwijderen",
    role: "Rol",
    roles: "Rollen",
    editor: "Redacteur",
    publisher: "Uitgever",
    name: "Naam",
    email: "E-mailadres",
    finishQuiz: "Quiz Voltooien",
    nextQuestion: "Volgende Vraag",
    selectQuizPrompt: "Selecteer een quiz om te beginnen.",
    quizCompleted: "Quiz Voltooid!",
    startQuiz: "Start Quiz",
    fillInTheBlanks: "Vul de Leemtes In",
    fillintheblanks: "Zoek het woord",
    fillInTheBlankInstruction: "Typ het ontbrekende Javaanse woord.",
    nextExercise: "Volgende Oefening",
    typeYourAnswer: "Typ hier je antwoord...",
    showAnswer: "Toon Antwoord",
    missingWordWas: "Het ontbrekende woord was:",
    noFillExercises: "Momenteel geen invuloefeningen beschikbaar.",
    noFillExercisesForLevel: "Momenteel geen invuloefeningen beschikbaar voor het geselecteerde niveau. Probeer een ander filter.",
    noHintAvailable: "Geen hint beschikbaar.",
    showJavaneseFirst: "Toon Javaans Eerst",
    selectLevel: "Selecteer Niveau",
    selectStatus: "Selecteer Status",
    selectSpeechLevel: "Selecteer Taalniveau",
    beginner: "Beginner",
    intermediate: "Gemiddeld",
    advanced: "Gevorderd",
    allLevels: "Alle Niveaus",
    filterByLevel: "Filter op Niveau:",
    draft: "Concept",
    published: "Gepubliceerd",
    archived: "Gearchiveerd",
    ngoko: "Ngoko (Informeel)",
    krama: "Krama (Formeel)",
    madya: "Madya (Semi-formeel)",
    neutral: "Neutraal",
    other: "Anders",
    english: "Engels",
    lessonSaved: "Les Opgeslagen",
    lessonPublished: "Les Gepubliceerd",
    formValidationFailed: "Controleer het formulier op fouten.",
    noQuizzesAvailable: "Geen quizzen beschikbaar om te koppelen.",
    noWordsAvailable: "Geen woordenschatwoorden beschikbaar om te koppelen.",
    lessonImageURL: "Les Afbeelding URL (optioneel)",
    lessonAudioURL: "Les Audio URL (optioneel)",
    imageURL: "Afbeelding URL",
    audioURL: "Audio URL",
    preview: "Voorbeeld (gesimuleerd)",
    translateWordDutch: "Vertaal woord naar Nederlands:",
    translateSentenceDutch: "Vertaal zin naar Nederlands:",
    translateWordJavanese: "Vertaal woord naar Javaans:",
    translateSentenceJavanese: "Vertaal zin naar Javaans:",
    fillInTheBlankMCQ: "Maak de zin compleet:",
    aiAssistContent: "AI Assistentie Inhoud",
    aiAssistComplete: "AI Assistentie Voltooid",
    aiAssistError: "AI Assist Error",
    manageUserRoles: "Gebruikersrollen Beheren",
    selectRolesForUser: "Selecteer de rollen voor deze gebruiker.",
    assignableRoles: "Toewijsbare Rollen",
    saveRoles: "Rollen Opslaan",
    userRolesUpdated: "Gebruikersrollen Bijgewerkt",
    rolesFor: "Rollen voor",
    haveBeenSaved: "zijn opgeslagen.",
    todaysFocus: "Focus van Vandaag",
    yourLearningJourney: "Jouw Leerreis",
    continueLearning: "Ga Verder Met Leren",
    resumeGrammar: "Hervat Grammatica:",
    tryNewQuiz: "Probeer een Nieuwe Quiz:",
    practicePronunciation: "Oefen Uitspraak:",
    discoverMore: "Ontdek Meer",
    yourAchievements: "Jouw Prestaties",
    viewAllProgress: "Bekijk Alle Voortgang & Badges",
    viewedLesson: "Les bekeken",
    lessonNotFound: "Les Niet Gevonden",
    lessonNotFoundDesc: "De grammaticales die je zoekt bestaat niet of kon niet geladen worden.",
    backToLessons: "Terug naar Lessen",
    listenToLesson: "Luister naar Lesoverzicht",
    playingAudio: "Audio afspelen voor",
    simulatingPlayback: "Simuleert afspelen",
    audioNotAvailable: "Audio Niet Beschikbaar",
    noAudioFor: "Geen audio voor",
    practiceExercises: "Oefeningen",
    applyWhatLearned: "Pas toe wat je hebt geleerd met deze interactieve oefeningen.",
    relatedVocabulary: "Gerelateerde Woordenschat",
    keyWordsRelated: "Sleutelwoorden gerelateerd aan deze les.",
    practiceInFlashcards: "Oefen deze woorden in Flashcards",
    relatedQuizzes: "Gerelateerde Quizzen",
    testYourUnderstanding: "Test je begrip van concepten uit deze les.",
    lessonRelatesToQuiz: "Deze les relateert aan de quiz:",
    quizPageNote: "(Dit brengt je naar de hoofd Quizzen pagina waar je deze quiz kunt selecteren.)",
    tryAgain: "Probeer Opnieuw",
    checkMasteryAndComplete: "Controleer Meesterschap & Voltooi Les",
    masteryNote: "Meesterschap vereist dat alle ingebedde oefeningen bij de eerste poging correct zijn.",
    completeAllExercises: "Onvolledig",
    attemptAllEmbeddedExercises: "Probeer alle ingebedde oefeningen voordat u meesterschap controleert.",
    lessonMastered: "Les Beheerst!",
    congratsPerfectEmbedded: "Gefeliciteerd! Je hebt alle ingebedde oefeningen perfect voltooid bij de eerste poging.",
    masteryNotAchieved: "Meesterschap Niet Behaald",
    reviewAndRetryLesson: "Niet alle oefeningen waren correct bij de eerste poging. Bekijk de stof opnieuw en probeer de les nogmaals (bijv. door opnieuw te navigeren) voor een nieuwe poging tot meesterschap.",
  },
};

interface LanguageProviderProps {
  children: ReactNode;
  passedLocale: Language;
}

export function LanguageProvider({ children, passedLocale }: LanguageProviderProps) {
  const router = useRouter();
  const pathname = usePathname();

  const language = passedLocale;

  useEffect(() => {
    localStorage.setItem('javaneseJourneyLanguagePref', language);
  }, [language]);


  const toggleLanguage = () => {
    const newLanguage = language === 'en' ? 'nl' : 'en';

    let newPath = pathname;
    if (pathname.startsWith(`/${language}`)) {
      newPath = pathname.substring(`/${language}`.length);
      if (newPath === "") newPath = "/";
    }

    router.push(`/${newLanguage}${newPath}`);
  };

  const currentTranslations = translationsData[language] || translationsData.nl;

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, translations: currentTranslations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

    